<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih salah satu   AGRI</name>
   <tag></tag>
   <elementGuidId>e50cfbb2-97f2-423c-bf6b-402a72e81562</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>bankName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inp_namaBank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bankName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
   						Pilih salah satu
   						AGRISAGRONIAGAANGLOMASANZ INDONESIAARTHA GRAHAARTOSBANGKOK BANKBANK ANDARABANK ANTAR DAERAHBANK DKIBANK DKI SYARIAHBANK INDONESIABANK JABAR BANTEN SYARIAHBANK JATIMBANK JATIM SYARIAHBANK NATIONALNOBUBANK OF AMERICABANK OF CHINABANK OF INDIA INDONESIABANK PEMBANGUNAN DAERAH JATENGBANK ROYALBANK SAHABAT SAMPOERNABANK SULUTBARCLAYSBCABCA SYARIAHBEIBIIBII SYARIAHBISNIS INTERNATIONALBNIBNI SYARIAHBNPBNP PARIBASBPD ACEHBPD ACEH SYARIAHBPD BALIBPD BENGKULUBPD JAMBIBPD KALBARBPD KALBAR SYARIAHBPD KALSELBPD KALSEL SYARIAHBPD KALTENGBPD KALTIMBPD KALTIM SYARIAHBPD LAMPUNGBPD MALUKUBPD NTBBPD NTTBPD PAPUABPD RIAU KEPRIBPD SULAWESI TENGGARABPD SULTENGBPD SUMBARBPD SUMSELBABELBPD SUMUTBPD SUMUT SYARIAHBPD YOGYAKARTABRIBRI SYARIAHBTNBTN SYARIAHBTPNBTPN SYARIAHBUKOPINBUKOPIN SYARIAHBUMI ARTACAPITAL INDONESIACENTRATAMA NASIONALCHINATRUSTCIMB NIAGACIMB NIAGA SYARIAHCITIBANKCOMMONWEALTHDANAMONDANAMON SYARIAHDBSDEUTSCHE BANKEKONOMIFAMA INTERNATIONALGANESHAHARDA INTERNASIONALHIMPUNAN SAUDARA 1906HSBCICBC INDONESIAINDEX SELINDOJABAR BANTENJASA JAKARTAJPMORGAN CHASEKEB HANA INDONESIAKESEJAHTERAAN EKONOMIMANDIRIMANDIRI SYARIAHMASPIONMAYAPADAMAYBANKMAYORAMEGAMEGA SYARIAHMESTIKA DHARMAMETRO EKSPRESSMITRANIAGAMIZUHOMNC INTERNASIONALMUAMALATMULTIARTA SENTOSAMUTIARAOCBC NISPPANINPANIN SYARIAHPERMATAPERMATA SYARIAHPRIMA MASTERPT. BANK DINAR INDONESIA TBKPT. BANK QNB KESAWAN, TBKPT. BANK SULSELBARPUNDIRABOBANKRESONA PERDANIASBI INDONESIASINAR HARAPAN BALISINARMASSINARMAS SYARIAHSTANCHARTSUMITOMO MITSUISUMSEL BABEL UUSTHE ROYAL BANK OF SCOTLANDTOKYO MITSUBISHIUOB BUANAVICTORIAVICTORIA SYARIAHWINDU KENTJANAWOORIYUDHA BHAKTI
   					</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inp_namaBank&quot;)</value>
   </webElementProperties>
</WebElementEntity>
