<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Karir</name>
   <tag></tag>
   <elementGuidId>288a9d43-d4c9-46f2-b8fe-28533f0e4c6e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://career.tunaiku.com/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Karir</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/landing-component[1]/overall-footer[1]/footer[@class=&quot;footer__wrapper&quot;]/div[@class=&quot;footer__container&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;list list--inline list--nested-block list-circleless&quot;]/li[1]/ul[1]/li[3]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
